name: flutter_getx_base
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  awesome_dialog: ^3.1.0
  barcode: ^2.2.4
  barcode_scan2: ^4.2.4
  barcode_widget: ^2.0.4
  cached_network_image: ^3.2.3
  camera: ^0.10.5+5
  contacts_service: ^0.6.3
  csv: ^5.1.0
  cupertino_icons: ^1.0.5
  dio: ^5.3.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_slidable: ^0.6.0
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.0
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.6.0
  freezed: ^2.3.2
  freezed_annotation: 2.2.0
  gallery_saver: ^2.3.2
  get: ^4.6.5
  google_mobile_ads: ^3.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  intl_phone_field: ^3.2.0
  loading_animation_widget: ^1.2.0+4
  lottie: ^2.7.0
  package_info_plus: ^4.2.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  photo_view: ^0.14.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  scan: ^1.6.0
  screenshot: ^2.1.0
  share_it: ^0.7.0
  share_plus: ^7.2.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.2.1
  uuid: ^4.1.0
  vibration: ^1.8.3
  wave: ^0.2.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
